# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.network "private_network", ip: "10.100.100.110"

    config.vm.provision "shell", path: "vagrant/install_common.sh"
    config.vm.provision "shell", path: "vagrant/install_node.sh"
    config.vm.provision "shell", path: "vagrant/install_nginx.sh"

    config.vm.provision "shell", path: "vagrant/install_project_dependencies.sh", privileged: false
    config.vm.provision "shell", path: "vagrant/configure_project.sh", privileged: false

    # Configure shell for user and root
    config.vm.provision "shell", path: "vagrant/configure_shell.sh", privileged: false
    config.vm.provision "shell", path: "vagrant/configure_shell.sh", privileged: true

    # Local script (not included by default)
    if File.exist?("vagrant/_local.sh") then
        config.vm.provision "shell", path: "vagrant/_local.sh", privileged: false
    end

    # Restart nginx server (/vagrant directory should be already mounted)
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        service nginx restart
    SHELL
end
